// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agosjbxdcmjsfyzvtuva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnb3NqYnhkY21qc2Z5enZ0dXZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDQ0OTIsImV4cCI6MjA3MjQ4MDQ5Mn0.4l24LuZw3aanqZPA-nPtOFTTmmCV8ifM76qxv9AlVbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});